runtime: nodejs20

env_variables:
  MONGODB_URI: mongodb+srv://admin:c9CREVyQ2d5SD9je@cluster0.3cihjsb.mongodb.net/backendcs?retryWrites=true&w=majority
  RAZORPAY_SECRET: OkDzY02Ps4FUp3MAtOLvI5Mn
  RAZORPAY_KEY_ID: rzp_test_kFK7Ig7iXkmRrX
  RESEND_API_KEY: re_j4hk87J8_3jK5r8qwtrZNsgs5Gn9stmZZ

handlers:
- url: /.*
  script: auto
  secure: always

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "20"
